/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/register": {
    /** Register a new user with email and password */
    post: operations["auth.register"];
  };
  "/login": {
    /** Login with email and password */
    post: operations["auth.login"];
  };
  "/roles": {
    /** Get available user roles */
    get: operations["auth.roles"];
  };
  "/user/profile": {
    /** Update the authenticated user's profile */
    put: operations["auth.updateProfile"];
  };
  "/user/password": {
    /** Change the authenticated user's password */
    put: operations["auth.changePassword"];
  };
  "/logout": {
    /** Logout the current user */
    post: operations["auth.logout"];
  };
  "/campaigns/public": {
    /** Display a paginated list of all campaigns (Public API) */
    get: operations["campaign.publicIndex"];
  };
  "/campaigns": {
    /** Display a list of all created campaigns by the authenticated user */
    get: operations["campaign.index"];
    /** Store a newly created campaign in storage for the authenticated user */
    post: operations["campaign.store"];
  };
  "/categories": {
    get: operations["dictionary.categories"];
  };
  "/content-styles": {
    get: operations["dictionary.contentStyles"];
  };
  "/platforms": {
    get: operations["dictionary.platforms"];
  };
  "/video-formats": {
    get: operations["dictionary.videoFormats"];
  };
  "/email/verification-notification": {
    /** Resend the email verification notification */
    post: operations["emailVerification.resend"];
  };
  "/email/verify/{id}/{hash}": {
    /** Mark the authenticated user's email address as verified */
    get: operations["verification.verify"];
  };
  "/password/forgot": {
    /** Send a password reset link to the user's email */
    post: operations["passwordReset.forgotPassword"];
  };
  "/password/reset": {
    /** Reset the user's password */
    post: operations["passwordReset.resetPassword"];
  };
  "/login/google": {
    /** Login or register with Google */
    post: operations["socialAuth.loginWithGoogle"];
  };
  "/login/apple": {
    /** Login or register with Apple */
    post: operations["socialAuth.loginWithApple"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Campaign */
    Campaign: {
      id: string;
      title: string;
      description: string;
      platforms: unknown[];
      min_duration: number;
      max_duration: number;
      content_styles: unknown[] | null;
      video_formats: unknown[] | null;
      /** Format: date-time */
      deadline: string;
      additional: string | null;
      number_of_creators: number;
      age_min: number;
      age_max: number;
      gender: string;
      cpm_rate: string;
      total_budget: string;
      verified_creator_only: boolean;
      require_portfolio_review: boolean;
      minimum_10k_followers: boolean;
      status: string;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
      user_id: number;
    };
    /** Category */
    Category: {
      code: string;
      title: string;
      icon: string;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      current_password: string;
      password: string;
      password_confirmation: string;
    };
    /** ContentStyle */
    ContentStyle: {
      code: string;
      title: string;
      icon: string;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /** Format: email */
      email: string;
    };
    /** LengthAwarePaginator */
    LengthAwarePaginator: {
      current_page: number;
      data: string;
      first_page_url: string;
      from: number | null;
      last_page: number;
      last_page_url: string;
      links: {
        [key: string]: unknown;
      };
      next_page_url: string;
      path: string | null;
      per_page: number;
      prev_page_url: string | null;
      to: number | null;
      total: number;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
      device_name?: string | null;
    };
    /** MessageBag */
    MessageBag: {
      [key: string]: string[];
    };
    /** Platform */
    Platform: {
      code: string;
      title: string;
      icon: string;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
    /** RegisterRequest */
    RegisterRequest: {
      name: string;
      /** Format: email */
      email: string;
      password: string;
      /** @enum {string} */
      role?: "creator" | "company";
      password_confirmation: string;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      token: string;
      /** Format: email */
      email: string;
      password: string;
      password_confirmation: string;
    };
    /** SocialLoginRequest */
    SocialLoginRequest: {
      access_token: string;
      device_name?: string | null;
    };
    /** UpdateProfileRequest */
    UpdateProfileRequest: {
      name?: string;
      /** Format: email */
      email?: string;
      /** Format: uri */
      avatar?: string | null;
      /** @enum {string} */
      role?: "creator" | "company";
    };
    /** UserResource */
    UserResource: {
      id: number;
      name: string;
      email: string;
      role: string;
      avatar: string | null;
      providers: {
        [key: string]: unknown;
      };
      has_password: boolean;
      email_verified_at: string;
      created_at: string;
    };
    /** VideoFormat */
    VideoFormat: {
      code: string;
      title: string;
      icon: string;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
  };
  responses: {
    /** @description Validation error */
    ValidationException: {
      content: {
        "application/json": {
          /** @description Errors overview. */
          message: string;
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[];
          };
        };
      };
    };
    /** @description Unauthenticated */
    AuthenticationException: {
      content: {
        "application/json": {
          /** @description Error overview. */
          message: string;
        };
      };
    };
    /** @description Authorization error */
    AuthorizationException: {
      content: {
        "application/json": {
          /** @description Error overview. */
          message: string;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Register a new user with email and password */
  "auth.register": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": {
            success: boolean;
            data: {
              user: components["schemas"]["UserResource"];
              token: string;
            };
            /** @enum {string} */
            message: "Registration successful. Please verify your email.";
          };
        };
      };
      422: components["responses"]["ValidationException"];
    };
  };
  /** Login with email and password */
  "auth.login": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: {
              user: components["schemas"]["UserResource"];
              token: string;
            };
            /** @enum {string} */
            message: "Login successful";
          };
        };
      };
      400: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "This account uses OAuth login. Please login with Google or Apple.";
            errors: null;
          };
        };
      };
      401: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Invalid credentials";
            errors: null;
          };
        };
      };
      422: components["responses"]["ValidationException"];
    };
  };
  /** Get available user roles */
  "auth.roles": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: ["creator", "company"];
            /** @enum {string} */
            message: "Available roles retrieved successfully";
          };
        };
      };
    };
  };
  /** Update the authenticated user's profile */
  "auth.updateProfile": {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["UserResource"];
            /** @enum {string} */
            message: "Profile updated successfully";
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
      422: components["responses"]["ValidationException"];
    };
  };
  /** Change the authenticated user's password */
  "auth.changePassword": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Password changed successfully";
          };
        };
      };
      400: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Current password is incorrect";
            errors: null;
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
      422: components["responses"]["ValidationException"];
    };
  };
  /** Logout the current user */
  "auth.logout": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Logged out successfully";
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
    };
  };
  /** Display a paginated list of all campaigns (Public API) */
  "campaign.publicIndex": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["LengthAwarePaginator"];
            /** @enum {string} */
            message: "Public campaigns retrieved successfully";
          };
        };
      };
    };
  };
  /** Display a list of all created campaigns by the authenticated user */
  "campaign.index": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["Campaign"][];
            /** @enum {string} */
            message: "User campaigns retrieved successfully";
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
    };
  };
  /** Store a newly created campaign in storage for the authenticated user */
  "campaign.store": {
    requestBody: {
      content: {
        "application/json": {
          title: string;
          description: string;
          min_duration: number;
          max_duration: number;
          /** Format: date-time */
          deadline: string;
          additional?: string | null;
          number_of_creators: number;
          age_min: number;
          age_max: number;
          /** @enum {string} */
          gender: "all" | "male" | "female";
          cpm_rate: number;
          total_budget: number;
          verified_creator_only?: boolean;
          require_portfolio_review?: boolean;
          minimum_10k_followers?: boolean;
          /** @enum {string|null} */
          status?: "open" | "closed";
          platforms: string[];
          content_styles?: string[] | null;
          video_formats?: string[] | null;
        };
      };
    };
    responses: {
      201: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["Campaign"];
            /** @enum {string} */
            message: "Campaign created successfully";
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
      422: components["responses"]["ValidationException"];
    };
  };
  "dictionary.categories": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["Category"][];
          };
        };
      };
    };
  };
  "dictionary.contentStyles": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["ContentStyle"][];
          };
        };
      };
    };
  };
  "dictionary.platforms": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["Platform"][];
          };
        };
      };
    };
  };
  "dictionary.videoFormats": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: components["schemas"]["VideoFormat"][];
          };
        };
      };
    };
  };
  /** Resend the email verification notification */
  "emailVerification.resend": {
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Verification email sent";
          };
        };
      };
      400: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Email already verified";
            errors: null;
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
    };
  };
  /** Mark the authenticated user's email address as verified */
  "verification.verify": {
    parameters: {
      path: {
        id: string;
        hash: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Email verified successfully";
          } | {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Email already verified";
          };
        };
      };
      401: components["responses"]["AuthenticationException"];
      403: components["responses"]["AuthorizationException"];
      422: components["responses"]["ValidationException"];
    };
  };
  /** Send a password reset link to the user's email */
  "passwordReset.forgotPassword": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Password reset link sent to your email";
          };
        };
      };
      422: components["responses"]["ValidationException"];
      500: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Unable to send password reset link";
            errors: null;
          };
        };
      };
    };
  };
  /** Reset the user's password */
  "passwordReset.resetPassword": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: null;
            /** @enum {string} */
            message: "Password has been reset successfully";
          };
        };
      };
      400: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Invalid or expired reset token" | "Unable to reset password";
            errors: null;
          };
        };
      };
      422: components["responses"]["ValidationException"];
    };
  };
  /** Login or register with Google */
  "socialAuth.loginWithGoogle": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SocialLoginRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: {
              user: components["schemas"]["UserResource"];
              token: string;
            };
            /** @enum {string} */
            message: "Login successful";
          };
        };
      };
      401: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Invalid OAuth token";
            errors: null;
          };
        };
      };
      422: components["responses"]["ValidationException"];
    };
  };
  /** Login or register with Apple */
  "socialAuth.loginWithApple": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SocialLoginRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            success: boolean;
            data: {
              user: components["schemas"]["UserResource"];
              token: string;
            };
            /** @enum {string} */
            message: "Login successful";
          };
        };
      };
      401: {
        content: {
          "application/json": {
            success: boolean;
            /** @enum {string} */
            message: "Invalid OAuth token";
            errors: null;
          };
        };
      };
      422: components["responses"]["ValidationException"];
    };
  };
}
